# 서버 구동
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# 사이트 세팅 + 호출법
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "마음 창고"
email: inaexjoy@gmail.com
name: "이응(인애)"
description: "마음 창고가 꽉 차서 아무것도 담을 수 없을 때마다 표현한 것들을 한데 모은 마음 창고에 초대합니다"
url: "https://ybeom.github.io/inxside"
locale: "ko-KR"

# Build settings
theme: minima
plugins:
    - jekyll-feed

# 작가 소개
author:
    name: "이응(최인애)"
    # avator: /assets/images/yb_avator.png
    # bio:
    email: "inaexjoy@gmail.com"

# 리딩 파일 리소스
exclude:
    - config
    - README

encoding: "utf-8"

#sass/scss
sass:
    sass_dir: _sass
    style: compressed

#rendering output options
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

staticman:
    baseUrl: "https://staticman-ybeom.herokuapp.com"
    userName: "ybeom"
    repository: "inxside"
    branch: "main"
